/**:
  controller_manager:
    ros__parameters:
      update_rate: 1000

      # Existing controllers
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      joint_position_controller:
        type: iitgn_controllers/JointPositionController

      # Add effort-based gripper controller for Gazebo
      gripper_effort_controller:
        type: effort_controllers/JointGroupEffortController

      # Your existing gripper topic controller (for real robot)
      gripper_topic_controller:
        type: iitgn_controllers/GripperTopicController

      # Other existing controllers
      cartesian_velocity_controller:
        type: iitgn_controllers/CartesianVelocityController

      impedance_controller:
        type: iitgn_controllers/ImpedanceController

      move_to_start_controller:
        type: iitgn_controllers/MoveToStartController



/**:
  joint_state_broadcaster:
    ros__parameters:
      arm_id: "fr3"
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7
        - fr3_finger_joint1
        - fr3_finger_joint2

/**:
  joint_position_controller:
    ros__parameters:
      # Robot identification
      arm_id: "fr3"
      
      # PID Gains for each joint (7 joints for FR3)
      kp_gains: [400.0, 400.0, 400.0, 400.0, 250.0, 150.0, 50.0]
      kd_gains: [30.0, 30.0, 30.0, 30.0, 20.0, 15.0, 5.0]
      ki_gains: [10.0, 10.0, 10.0, 10.0, 5.0, 5.0, 2.0]
      
      target_position: [0.0, -0.785, 0.0, -2.356, 0.0, 1.571, 0.785]
      control_mode: "position_control"
      trajectory_duration: 5.0
      motion_amplitude: 0.5
      motion_frequency: 0.2
      command_topic: "/joint_position_command"

/**:
  gripper_effort_controller:
    ros__parameters:
      joints:
        - fr3_finger_joint1
        
      command_interfaces:
        - effort
      state_interfaces:
        - position
        - velocity
        - effort

/**:
  gripper_topic_controller:
    ros__parameters:
      # Robot arm ID
      arm_id: "fr3"
      
      # Topic for receiving gripper commands
      gripper_command_topic: "~/gripper_command"
      
      # Gripper parameters
      gripper_open_width: 0.08    # meters (fully open)
      gripper_close_width: 0.04  # meters (target grasp width)
      gripper_speed: 0.1          # meters/second
      gripper_force: 10.0        # Newtons
      
      # Epsilon parameters for grasp tolerance
      epsilon_inner: 0.03        # meters (minimum acceptable grasp)
      epsilon_outer: 0.03        # meters (maximum acceptable grasp)

/**:
  cartesian_velocity_controller:
    ros__parameters:
      arm_id: "fr3"

/**:
  impedance_controller:
    ros__parameters:
      arm_id: "fr3"
      command_topic: "/impedance_command"
      k_gains:
        - 24.0
        - 24.0
        - 24.0
        - 24.0
        - 10.0
        - 6.0
        - 2.0
      d_gains:
        - 2.0
        - 2.0
        - 2.0
        - 1.0
        - 1.0
        - 1.0
        - 0.5
      m_gains:
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
      impedance_mode: "compliance_motion"
      compliance_factor: 0.5
      motion_amplitude: 0.3
      motion_frequency: 0.2
      target_position: [0.0, -0.785, 0.0, -2.356, 0.0, 1.571, 0.785]

/**:
  move_to_start_controller:
    ros__parameters:
      arm_id: "fr3"
      k_gains:
        - 600.0
        - 600.0
        - 600.0
        - 600.0
        - 250.0
        - 150.0
        - 50.0
      d_gains:
        - 30.0
        - 30.0
        - 30.0
        - 30.0
        - 10.0
        - 10.0
        - 5.0

