name: ROS 2 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04   # <-- instead of ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ROS 2 Humble
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          rosdep update
          rosdep install --from-paths . --ignore-src -y --rosdistro humble
      

      - name: Build workspace
        run: |
          colcon build --event-handlers console_direct+

      - name: Install ROS 2 test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-ament-copyright \
            python3-ament-flake8 \
            python3-ament-pep257



